-- CUSTOMER Table
CREATE OR REPLACE TABLE CUSTOMER (
    custNr VARCHAR(255) PRIMARY KEY,
    fullName VARCHAR(255)
);

-- SUBSCR Table
CREATE OR REPLACE TABLE SUBSCR (
    acctId VARCHAR(255) PRIMARY KEY,
    custId VARCHAR(255) PRIMARY KEY REFERENCES CUSTOMER(custNr),
    phoneNo VARCHAR(255),
    active NUMBER,
    acctActiveYN CHAR
);