name: RAI Workflow Manager EA Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  Run-RWM-Tests:
    runs-on: ubuntu-latest
    steps:
      # Install Python
      - run: echo "Installing Python"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Checkout code repo
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install Python dependencies
        run: |
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install $GITHUB_WORKSPACE

      # Setup config required for Python CLI run
      - name: Config setup
        run: |
          mkdir ~/.rai
          cd ~/.rai
          echo "[default]" > config
          echo "region = us-east" >> config
          echo "host = azure-ea.relationalai.com" >> config
          echo "client_credentials_url = https://login-ea.relationalai.com/oauth/token" >> config
          echo "port = 443" >> config
          echo "client_id = ${{ secrets.EA_CLIENT_ID }}" >> config
          echo "client_secret = ${{ secrets.EA_CLIENT_SECRET }}" >> config

      # Generate unique id
      - name: Generate unique id
        id: unique_id
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Generate RAI resource name
      - id: generate-resource-name
        name: Generate prefix
        run: |
          echo "resource_id=wm-cli-e2e-test-${{ steps.unique_id.outputs.sha_short }}" >> $GITHUB_OUTPUT
        shell: bash

      # Update loader
      - name: Update loader
        run: |
          cd $GITHUB_WORKSPACE/cli-e2e-test/config
          sed -i '1irai_cloud_account="${{ secrets.RAI_CLOUD_ACCOUNT }}"' loader.toml
          sed -i '1isematic_search_pod_prefix="${{ steps.generate-resource-name.outputs.resource_id }}-"' loader.toml

      # Checkout semantic layer service
      - name: Checkout semantic layer service
        uses: actions/checkout@v3
        with:
          repository: RelationalAI/semantic-search
          path: semantic-search
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and run Semantic Layer service
      - name: Build and run Semantic Layer service
        run: |
          cd $GITHUB_WORKSPACE/semantic-search
          ./docker-build
          docker run --rm -d --name testServer -p 8081:8081 semantic-search:latest

      # Run e2e Python CLI test
      - name: Python CLI tests
        run: |
          cd $GITHUB_WORKSPACE/cli-e2e-test
          python -m unittest discover
        env:
          RAI_RESOURCE_NAME: ${{ steps.generate-resource-name.outputs.resource_id }}

      # Shutdown Semantic Layer service
      - name: Shutdown Semantic Layer service container
        run: docker stop testServer
        if: always()

