name: RAI Workflow Manager Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Run-Fraud-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Install Python
      - run: echo "Installing Python"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Checkout code repo
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install Python dependencies
        run: |
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install $GITHUB_WORKSPACE

      # Run Workflow tests
      - name: Python Workflow Manager tests
        run: |
          cd $GITHUB_WORKSPACE/test
          python -m unittest discover

      # Setup config required for Python CLI run
      - name: Config setup
        run: |
          mkdir ~/.rai
          cd ~/.rai
          echo "[default]" > config
          echo "region = us-east" >> config
          echo "host = azure.relationalai.com" >> config
          echo "port = 443" >> config
          echo "client_id = ${{ env.RAI_CLIENT_ID }}" >> config
          echo "client_secret = ${{ env.RAI_CLIENT_SECRET }}" >> config
          # Create empty toml
          cd $GITHUB_WORKSPACE/cli-e2e-test/config
          touch loader.toml
        env:
          RAI_CLIENT_ID: ${{ secrets.client_id }}
          RAI_CLIENT_SECRET: ${{ secrets.client_secret }}

      # Run e2e Python CLI test
      - name: Python CLI tests
        run: |
          cd $GITHUB_WORKSPACE/cli-e2e-test
          python -m unittest discover
